# Hyperparameters
desired_batch_size: 32
batch_size: 32
num_steps: 10560  # 704 steps is one epoch
n_val_shards: 3

# lr scheduler
# max steps: ~1epoch | warmup_steps: int(config['max_steps'] * 0.037) based on nanogpt | max_lr 3e-4 | min_lr: 3e-5
max_steps: 704
warmup_steps: 27
max_lr: 0.001
min_lr: 0.0001

# Model Configuration
model_name: ""  # faster-rcnn has only one model config so using that as default
pretrained_flag: true

# Dataset & DataLoader Configuration
dataset_path: "/scratch/rawhad/CSE507/practice_2_v2/shards"
num_workers: 1
prefetch_factor: 96
shard_size: 1024

# Training and Checkpointing
eval_interval: 704
ckpt_interval: 704
ckpt_dir: "/scratch/rawhad/CSE507/practice_2_v2/models"
do_ckpt: true

# Run/Experiment Configuration
run_name: "v2_finetuning_test"
project_name: "cse507_practice2"

# Custom
class_mapping:
  No finding: 0
  Aortic enlargement: 1
  Atelectasis: 2
  Calcification: 3
  Cardiomegaly: 4
  Consolidation: 5
  ILD: 6
  Infiltration: 7
  Lung Opacity: 8
  Nodule/Mass: 9
  Other lesion: 10
  Pleural effusion: 11
  Pleural thickening: 12
  Pneumothorax: 13
  Pulmonary fibrosis: 14
